// <auto-generated />
namespace DarAlArqamForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ver3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ver3));
        
        string IMigrationMetadata.Id
        {
            get { return "202310070149231_ver3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
